About the language problem of README.md
ent/ent pull request #1235
Opened 2021-02-04 07:38 UTC by yunteng9345

Go language is becoming more and more popular in China. ent is a very powerful framework, and many Chinese people will learn various Go language frameworks。

2021-02-04 14:29 UTC, a8m commented
Thanks for your contribution @yunteng9345, it's appreciated. 

@hantmac - any chance you can help reviewing this? 🙏

2021-02-10 03:16 UTC, roger2hk requested changes
Please rename `README_zh.md` to `README_zh_CN.md` for zh_TW, zh_HK, zh_MO and zh_SG locale support later.

2021-02-10 03:16 UTC, roger2hk commented on README_zh.md
> +使用[Go modules]进行正确安装，请访问[entgo.io website][entgo instal]。
```suggestion
请访问[entgo.io website][entgo instal]以使用[Go modules]进行正确安装。
```

2021-02-10 03:16 UTC, roger2hk commented on README_zh.md
> +讨论问题和支持, [创建一个issue](https://github.com/facebook/ent/issues/new/choose) 或者加入我们的Gopher Slack(Slack软件,类似于论坛)[讨论组](https://gophers.slack.com/archives/C01FMSQDT53)
```suggestion
如要讨论问题和支持, [创建一个issue](https://github.com/facebook/ent/issues/new/choose) 或者加入我们的Gopher Slack(Slack软件,类似于论坛)[讨论组](https://gophers.slack.com/archives/C01FMSQDT53)  
```

2021-02-10 03:32 UTC, yunteng9345 commented
> Please rename `README_zh.md` to `README_zh_CN.md` for zh_TW, zh_HK, zh_MO and zh_SG locale support later.

好想法！

2021-02-12 11:53 UTC, a8m commented
Thanks for the review @roger2hk, it's appreciated!

2021-02-12 11:54 UTC, merged