deps: bump atlas (issue with current version of atlas due to an argum…
ent/ent pull request #2521
Opened 2022-05-04 08:17 UTC by masseelch

…ent change in NewDriver)

Signed-off-by: MasseElch <github@masseelch.de>

2022-05-04 08:18 UTC, a8m approved these changes

2022-05-04 08:18 UTC, hedwigz approved these changes

2022-05-04 09:02 UTC, masseelch commented
@alexsn Sorry to bother you, your initial setup of the CI ran the integration tests on master in every PR. Is there any special reason for that (I am not sure I know why this is done).

2022-05-05 04:46 UTC, a8m commented
> @alexsn Sorry to bother you, your initial setup of the CI ran the integration tests on master in every PR. Is there any special reason for that (I am not sure I know why this is done).

The `migration` step was added by me to check that migrating from the master version to the new version is safe and keeps BC (on an existing database). Please, keep it as it prevented a few issues in the past.

2022-05-05 04:46 UTC, a8m commented on .github/workflows/ci.yml
> -      - name: Run integration on HEAD
keep it

2022-05-05 04:49 UTC, a8m requested changes
Please, revert the CI changes.

2022-05-05 06:25 UTC, a8m approved these changes

2022-05-05 06:30 UTC, merged